spring.application.name=SchoolManagement

app.name=StudentManagementSystem
app.version=1.1.1

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/SchoolSystem
spring.datasource.username=postgres
spring.datasource.password=Shaly21

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update



spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.jpa.show-sql=true